# https://containers.dev/guide/dockerfile
volumes:
  postgres_data:
  # pgadmin_data:

services:
  application:
    container_name: python-dev-tools
    # https://github.com/devcontainers/images/blob/main/src/python/README.md
    image: "mcr.microsoft.com/devcontainers/python:3.11-bullseye"
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

  db:
    container_name: python-dev-tools-db
    image: postgres:16.8-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@test.com
  #     PGADMIN_DEFAULT_PASSWORD: Admin1234
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin